### ISSUE TITLE
Thank you for all you done

### ISSUE THREAD

**Issue by jean-pasqualini** [PHPFastCGI/FastCGIDaemon#19]
Put +1 to support my message

░░░░░░░░░░░░▄▄
░░░░░░░░░░░█░░█
░░░░░░░░░░░█░░█
░░░░░░░░░░█░░░█
░░░░░░░░░█░░░░█
███████▄▄█░░░░░██████▄
▓▓▓▓▓▓█░░░░░░░░░░░░░░█
▓▓▓▓▓▓█░░░░░░░░░░░░░░█
▓▓▓▓▓▓█░░░░░░░░░░░░░░█
▓▓▓▓▓▓█░░░░░░░░░░░░░░█
▓▓▓▓▓▓█░░░░░░░░░░░░░░█
▓▓▓▓▓▓█████░░░░░░░░░█
██████▀░░░░▀▀██████▀

**Comment by AndrewCarterUK** [comment]
You're welcome!

Never thought I'd have to create an 'appreciation' label on GitHub!
