### ISSUE TITLE
Yii2: expected more significant performance improvement.

### ISSUE THREAD

**Issue by m0onspell** [PHPFastCGI/FastCGIDaemon#29]
I've described my situation here: yiisoft/yii2#14646
I did a quick and dirty integration between FastCGIDaemon and my Yii2 app.
With php-fpm I got ~5k rps. With FastCGIDaemon I reached ~8k rps.
I have nginx + 32 FastCGIDaemon workers, managed by supervisord.
Under the load of 8k rps, all 16 CPU cores are fully loaded.
That's a big improvement, sure, but I've expected much higher performance increase since now I get rid of bootstrapping framework on every request. My similar node.js application is still many times faster on same machine.
I wonder if this is expected level of performance increase? 
 What else can I try?

**Comment by AndrewCarterUK** [comment]
I'd need to check the setup/logs/etc to see exactly what was going on. If the NGINX load balancer had a backend that was failing that could decrease the performance quite significantly.

It's also a case of how fast your setup was originally. 5k a second is quite fast for PHP - you can't have been bootstrapping much! Was there any caching happening?

Something that slows down PHPFastCGI a reasonable amount is actually creating the request objects from the FastCGI parameters - so you can speed it up by removing unnecessary ones.

How do you create the Yii2 request object? If you create it from a Http Foundation or PSR-7 request object then that will probably add a fair amount of time - you'd see a performance increase to create it directly from the FastCGI request object.

**Comment by AndrewCarterUK** [comment]
If you pasted your glue code from PHPFastCGI to Yii2 I'd be happy to take a look.

**Comment by m0onspell** [comment]
Thank you for a quick reply! 
I am reffering to both HttpFoundation and PSR-7 requests.

`index.php`:
```php
require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/../components/DaemonApplication.php');

use PHPFastCGI\FastCGIDaemon\ApplicationFactory;
use PHPFastCGI\FastCGIDaemon\Http\RequestInterface;
use app\components\DaemonApplication;
use Symfony\Component\HttpFoundation\Response;

$config = require(__DIR__ . '/../config/web.php');
$yiiApp = new DaemonApplication($config);

$application = (new ApplicationFactory)->createApplication(function (RequestInterface $request) use ($yiiApp) {
    try {
        $_SERVER = \yii\helpers\ArrayHelper::merge($_SERVER, $request->getServerRequest()->getServerParams());
        $_GET = $request->getServerRequest()->getQueryParams();
        $_POST = $request->getServerRequest()->getParsedBody();

        $yiiApp->getRequest()->setDaemonRequest($request);

        $yiiResponse = $yiiApp->run();
        $yiiResponse->prepareSendFromDaemon();

        $response = new Response(
            $yiiResponse->content,
            $yiiResponse->getStatusCode(),
            $yiiResponse->getHeaders()->toArray()
        );

        $yiiResponse->clear();

        return $response;
    } catch (\Exception $e) {
        return new Response($e->getMessage(), 500);
    }
});

$application->run();
```

I am extending Yii2 request class with following:
```php
namespace app\components;
use yii\web\HeaderCollection;
use yii\web\Request;
use PHPFastCGI\FastCGIDaemon\Http\RequestInterface;

class CustomRequest extends Request
{
    /**
     * @var RequestInterface
     */
    private $daemonRequest;

    private $_headersOverride;

    public function getQueryParams()
    {
        $_queryParams = parent::getQueryParams();
        return empty($_queryParams) ? $this->daemonRequest->getServerRequest()->getQueryParams() : $_queryParams;
    }

    public function getHeaders()
    {
        if ($this->_headersOverride === null) {
            $this->_headersOverride = new HeaderCollection;

            $headers = $this->daemonRequest->getHttpFoundationRequest()->headers->all();

            foreach ($headers as $name => $value) {
                $this->_headersOverride->add($name, $value);
            }
        }

        return $this->_headersOverride;
    }

    public function getRawBody()
    {
        return $this->daemonRequest->getHttpFoundationRequest()->getContent();
    }

    public function getPathInfo()
    {
        return $this->daemonRequest->getHttpFoundationRequest()->getPathInfo();
    }

    public function setDaemonRequest(RequestInterface $request)
    {
        $this->daemonRequest = $request;
    }
} 
```
There's also `DaemonApplication` class which extends standard `yii\web\Application`, with only one change: `Application::run()` method returns response object, instead of sending it immediately.

**Comment by m0onspell** [comment]
There was opcache enabled. Also enabled MySQL schema caching for ActiveRecord in Yii settings. No caching other then that.
My server is quite powerful with 16 cores. I also spent a lot of time optimizing different environment settings. Action that I am hitting in tests is just for ping, it performs authentication (redis and MySQL involved), and then just send 'OK' response.
That's why it's quite fast, I think. There's no errors, if I try to increase the load to more then 8k rps, I am starting to get very slow response time, and overall handled requests per minute number drops down.

**Comment by AndrewCarterUK** [comment]
Try calling getServerRequest() or getHttpFoundationRequest() only once and
storing the result.

**Comment by m0onspell** [comment]
@AndrewCarterUK, I did some refactoring in this direction, and that helped a lot! 10k rps, one minute test duration:
![screenshot from 2017-08-16 21 26 29](https://user-images.githubusercontent.com/8426911/29379056-d9e9e526-82c9-11e7-9c5c-853f3c30bf26.png)

And there are still some free CPU resources, so it can probably handle ~12k rps, I can't test more then 10k rps for now.
![screenshot from 2017-08-16 21 25 22](https://user-images.githubusercontent.com/8426911/29379113-03ae5504-82ca-11e7-9127-6f1f2833861c.png)

Thanks, man, I am happy that I opened this issue. I'll limit referring to `getServerRequest` and `getHttpFoundationRequest` to single calls, and this should give even more performance increase.

Node is still faster, but now the difference in performance is something that I can understand and explain by Express vs Yii2 size difference (Express is very minimalistic, very minimum features) and overall Node vs PHP performance difference, I guess.

**Comment by AndrewCarterUK** [comment]
Not a problem, happy to help.

To be honest, you can probably get away without creating any PSR-7 or Http Foundation request objects and just using the [PHPFastCGI request object](https://github.com/PHPFastCGI/FastCGIDaemon/blob/master/src/Http/RequestInterface.php). It has a couple of helper methods to extract $_GET, $_POST, $_SERVER and $_COOKIES.
