### ISSUE TITLE
Fails with large POST requests

### ISSUE THREAD

**Issue by gaaf** [PHPFastCGI/FastCGIDaemon#30]
When a large POST request comes in, my script dies. Input is read over STDIN. Smaller request have no issue.

`
PHP Notice:  Undefined offset: 0 in /home/alex/projects/fcgi/vendor/phpfastcgi/fastcgi-daemon/src/Driver/Userland/Connection/StreamSocketConnectionPool.php on line 70
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PHPFastCGI\FastCGIDaemon\Driver\Userland\ConnectionHandler\ConnectionHandlerFactory::createConnectionHandler() must implement interface PHPFastCGI\FastCGIDaemon\Driver\Userland\Connection\ConnectionInterface, null given, called in /home/alex/projects/fcgi/vendor/phpfastcgi/fastcgi-daemon/src/Driver/Userland/UserlandDaemon.php on line 102 and defined in /home/alex/projects/fcgi/vendor/phpfastcgi/fastcgi-daemon/src/Driver/Userland/ConnectionHandler/ConnectionHandlerFactory.php:16
Stack trace:
#0 /home/alex/projects/fcgi/vendor/phpfastcgi/fastcgi-daemon/src/Driver/Userland/UserlandDaemon.php(102): PHPFastCGI\FastCGIDaemon\Driver\Userland\ConnectionHandler\ConnectionHandlerFactory->createConnectionHandler(Object(PHPFastCGI\FastCGIDaemon\CallbackWrapper), NULL)
#1 /home/alex/projects/fcgi/vendor/phpfastcgi/fastcgi-daemon/src/Driver/Userland/UserlandDaemon.php(74): PHPFastCGI\FastCGIDaemon\Driver\Use in /home/alex/projects/fcgi/vendor/phpfastcgi/fastcgi-daemon/src/Driver/Userland/ConnectionHandler/ConnectionHandlerFactory.php on line 16
</code>
`

**Comment by AndrewCarterUK** [comment]
Thanks for this and the PR.

This will be tagged as v0.10.1
