### ISSUE TITLE
if i update the business code, how can i make it effective

### ISSUE THREAD

**Issue by ayamzh** [PHPFastCGI/FastCGIDaemon#34]
if i update the business code, how can i make it effective.     for example.in php fpm i can fpm reload

**Comment by AndrewCarterUK** [comment]
If you update your application, you'll need to restart your FastCGI workers. Hot code reload isn't supported.

**Comment by ayamzh** [comment]
can it be Graceful Restarted？

**Comment by Nyholm** [comment]
Sure, pcntl signals are supported.
